//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.Xuatnhapcanh.Dal.HelperClasses
{
	/// <summary>Field Creation Class for entity CustomsAnswerOptionEntity</summary>
	public partial class CustomsAnswerOptionFields
	{
		/// <summary>Creates a new CustomsAnswerOptionEntity.Content field instance</summary>
		public static EntityField2 Content { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsAnswerOptionFieldIndex.Content); }}
		/// <summary>Creates a new CustomsAnswerOptionEntity.DetailRequired field instance</summary>
		public static EntityField2 DetailRequired { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsAnswerOptionFieldIndex.DetailRequired); }}
		/// <summary>Creates a new CustomsAnswerOptionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsAnswerOptionFieldIndex.Id); }}
		/// <summary>Creates a new CustomsAnswerOptionEntity.QuestionId field instance</summary>
		public static EntityField2 QuestionId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsAnswerOptionFieldIndex.QuestionId); }}
	}

	/// <summary>Field Creation Class for entity CustomsImmigrationEntity</summary>
	public partial class CustomsImmigrationFields
	{
		/// <summary>Creates a new CustomsImmigrationEntity.Address field instance</summary>
		public static EntityField2 Address { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Address); }}
		/// <summary>Creates a new CustomsImmigrationEntity.Cash field instance</summary>
		public static EntityField2 Cash { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Cash); }}
		/// <summary>Creates a new CustomsImmigrationEntity.CityFrom field instance</summary>
		public static EntityField2 CityFrom { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.CityFrom); }}
		/// <summary>Creates a new CustomsImmigrationEntity.CityTo field instance</summary>
		public static EntityField2 CityTo { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.CityTo); }}
		/// <summary>Creates a new CustomsImmigrationEntity.Dob field instance</summary>
		public static EntityField2 Dob { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Dob); }}
		/// <summary>Creates a new CustomsImmigrationEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Email); }}
		/// <summary>Creates a new CustomsImmigrationEntity.EntryDate field instance</summary>
		public static EntityField2 EntryDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.EntryDate); }}
		/// <summary>Creates a new CustomsImmigrationEntity.FirstName field instance</summary>
		public static EntityField2 FirstName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.FirstName); }}
		/// <summary>Creates a new CustomsImmigrationEntity.Gender field instance</summary>
		public static EntityField2 Gender { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Gender); }}
		/// <summary>Creates a new CustomsImmigrationEntity.Goods field instance</summary>
		public static EntityField2 Goods { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Goods); }}
		/// <summary>Creates a new CustomsImmigrationEntity.HotelName field instance</summary>
		public static EntityField2 HotelName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.HotelName); }}
		/// <summary>Creates a new CustomsImmigrationEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Id); }}
		/// <summary>Creates a new CustomsImmigrationEntity.Jewellery field instance</summary>
		public static EntityField2 Jewellery { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Jewellery); }}
		/// <summary>Creates a new CustomsImmigrationEntity.LaneAssignment field instance</summary>
		public static EntityField2 LaneAssignment { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.LaneAssignment); }}
		/// <summary>Creates a new CustomsImmigrationEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.LastName); }}
		/// <summary>Creates a new CustomsImmigrationEntity.LeaveDate field instance</summary>
		public static EntityField2 LeaveDate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.LeaveDate); }}
		/// <summary>Creates a new CustomsImmigrationEntity.LuggageCount field instance</summary>
		public static EntityField2 LuggageCount { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.LuggageCount); }}
		/// <summary>Creates a new CustomsImmigrationEntity.Nationality field instance</summary>
		public static EntityField2 Nationality { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Nationality); }}
		/// <summary>Creates a new CustomsImmigrationEntity.PassportExpiredate field instance</summary>
		public static EntityField2 PassportExpiredate { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.PassportExpiredate); }}
		/// <summary>Creates a new CustomsImmigrationEntity.PassportNo field instance</summary>
		public static EntityField2 PassportNo { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.PassportNo); }}
		/// <summary>Creates a new CustomsImmigrationEntity.Status field instance</summary>
		public static EntityField2 Status { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Status); }}
		/// <summary>Creates a new CustomsImmigrationEntity.Transportation field instance</summary>
		public static EntityField2 Transportation { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Transportation); }}
		/// <summary>Creates a new CustomsImmigrationEntity.TransportationNo field instance</summary>
		public static EntityField2 TransportationNo { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.TransportationNo); }}
		/// <summary>Creates a new CustomsImmigrationEntity.Userid field instance</summary>
		public static EntityField2 Userid { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsImmigrationFieldIndex.Userid); }}
	}

	/// <summary>Field Creation Class for entity CustomsQuestionEntity</summary>
	public partial class CustomsQuestionFields
	{
		/// <summary>Creates a new CustomsQuestionEntity.Content field instance</summary>
		public static EntityField2 Content { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsQuestionFieldIndex.Content); }}
		/// <summary>Creates a new CustomsQuestionEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsQuestionFieldIndex.Id); }}
		/// <summary>Creates a new CustomsQuestionEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsQuestionFieldIndex.IsActive); }}
		/// <summary>Creates a new CustomsQuestionEntity.QuestionType field instance</summary>
		public static EntityField2 QuestionType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsQuestionFieldIndex.QuestionType); }}
	}

	/// <summary>Field Creation Class for entity CustomsTaxisEntity</summary>
	public partial class CustomsTaxisFields
	{
		/// <summary>Creates a new CustomsTaxisEntity.HsCode field instance</summary>
		public static EntityField2 HsCode { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsTaxisFieldIndex.HsCode); }}
		/// <summary>Creates a new CustomsTaxisEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsTaxisFieldIndex.Id); }}
		/// <summary>Creates a new CustomsTaxisEntity.Name field instance</summary>
		public static EntityField2 Name { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsTaxisFieldIndex.Name); }}
		/// <summary>Creates a new CustomsTaxisEntity.Origins field instance</summary>
		public static EntityField2 Origins { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsTaxisFieldIndex.Origins); }}
		/// <summary>Creates a new CustomsTaxisEntity.Quantity field instance</summary>
		public static EntityField2 Quantity { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsTaxisFieldIndex.Quantity); }}
		/// <summary>Creates a new CustomsTaxisEntity.Type field instance</summary>
		public static EntityField2 Type { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsTaxisFieldIndex.Type); }}
		/// <summary>Creates a new CustomsTaxisEntity.UsePurposes field instance</summary>
		public static EntityField2 UsePurposes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsTaxisFieldIndex.UsePurposes); }}
		/// <summary>Creates a new CustomsTaxisEntity.Value field instance</summary>
		public static EntityField2 Value { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsTaxisFieldIndex.Value); }}
	}

	/// <summary>Field Creation Class for entity CustomsUserAnswerEntity</summary>
	public partial class CustomsUserAnswerFields
	{
		/// <summary>Creates a new CustomsUserAnswerEntity.AnswerId field instance</summary>
		public static EntityField2 AnswerId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsUserAnswerFieldIndex.AnswerId); }}
		/// <summary>Creates a new CustomsUserAnswerEntity.AnswerText field instance</summary>
		public static EntityField2 AnswerText { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsUserAnswerFieldIndex.AnswerText); }}
		/// <summary>Creates a new CustomsUserAnswerEntity.ChoiceId field instance</summary>
		public static EntityField2 ChoiceId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsUserAnswerFieldIndex.ChoiceId); }}
		/// <summary>Creates a new CustomsUserAnswerEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsUserAnswerFieldIndex.CreatedAt); }}
		/// <summary>Creates a new CustomsUserAnswerEntity.ImmigrationFormId field instance</summary>
		public static EntityField2 ImmigrationFormId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsUserAnswerFieldIndex.ImmigrationFormId); }}
		/// <summary>Creates a new CustomsUserAnswerEntity.QuestionId field instance</summary>
		public static EntityField2 QuestionId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsUserAnswerFieldIndex.QuestionId); }}
		/// <summary>Creates a new CustomsUserAnswerEntity.UserId field instance</summary>
		public static EntityField2 UserId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(CustomsUserAnswerFieldIndex.UserId); }}
	}

	/// <summary>Field Creation Class for entity NewsEntity</summary>
	public partial class NewsFields
	{
		/// <summary>Creates a new NewsEntity.Content field instance</summary>
		public static EntityField2 Content { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(NewsFieldIndex.Content); }}
		/// <summary>Creates a new NewsEntity.Headline field instance</summary>
		public static EntityField2 Headline { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(NewsFieldIndex.Headline); }}
		/// <summary>Creates a new NewsEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(NewsFieldIndex.Id); }}
		/// <summary>Creates a new NewsEntity.NewsType field instance</summary>
		public static EntityField2 NewsType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(NewsFieldIndex.NewsType); }}
	}
	

}