//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using App.Xuatnhapcanh.Dal.FactoryClasses;
using App.Xuatnhapcanh.Dal.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.Xuatnhapcanh.Dal.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitCustomsAnswerOptionEntityInfo();
			InitCustomsImmigrationEntityInfo();
			InitCustomsQuestionEntityInfo();
			InitCustomsTaxisEntityInfo();
			InitCustomsUserAnswerEntityInfo();
			InitNewsEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits CustomsAnswerOptionEntity's info objects</summary>
		private void InitCustomsAnswerOptionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CustomsAnswerOptionFieldIndex), "CustomsAnswerOptionEntity");
			this.AddElementFieldInfo("CustomsAnswerOptionEntity", "Content", typeof(System.String), false, false, false, false,  (int)CustomsAnswerOptionFieldIndex.Content, 1000, 0, 0);
			this.AddElementFieldInfo("CustomsAnswerOptionEntity", "DetailRequired", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CustomsAnswerOptionFieldIndex.DetailRequired, 0, 0, 0);
			this.AddElementFieldInfo("CustomsAnswerOptionEntity", "Id", typeof(System.String), true, false, false, false,  (int)CustomsAnswerOptionFieldIndex.Id, 40, 0, 0);
			this.AddElementFieldInfo("CustomsAnswerOptionEntity", "QuestionId", typeof(System.String), false, true, false, true,  (int)CustomsAnswerOptionFieldIndex.QuestionId, 40, 0, 0);
		}

		/// <summary>Inits CustomsImmigrationEntity's info objects</summary>
		private void InitCustomsImmigrationEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CustomsImmigrationFieldIndex), "CustomsImmigrationEntity");
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Address", typeof(System.String), false, false, false, true,  (int)CustomsImmigrationFieldIndex.Address, 200, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Cash", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CustomsImmigrationFieldIndex.Cash, 0, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "CityFrom", typeof(System.String), false, false, false, true,  (int)CustomsImmigrationFieldIndex.CityFrom, 300, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "CityTo", typeof(System.String), false, false, false, true,  (int)CustomsImmigrationFieldIndex.CityTo, 300, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Dob", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CustomsImmigrationFieldIndex.Dob, 0, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Email", typeof(System.String), false, false, false, true,  (int)CustomsImmigrationFieldIndex.Email, 100, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "EntryDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CustomsImmigrationFieldIndex.EntryDate, 0, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "FirstName", typeof(System.String), false, false, false, true,  (int)CustomsImmigrationFieldIndex.FirstName, 40, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Gender", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CustomsImmigrationFieldIndex.Gender, 0, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Goods", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CustomsImmigrationFieldIndex.Goods, 0, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "HotelName", typeof(System.String), false, false, false, true,  (int)CustomsImmigrationFieldIndex.HotelName, 10485760, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Id", typeof(System.String), true, false, false, false,  (int)CustomsImmigrationFieldIndex.Id, 40, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Jewellery", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CustomsImmigrationFieldIndex.Jewellery, 0, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "LaneAssignment", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CustomsImmigrationFieldIndex.LaneAssignment, 0, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "LastName", typeof(System.String), false, false, false, true,  (int)CustomsImmigrationFieldIndex.LastName, 40, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "LeaveDate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CustomsImmigrationFieldIndex.LeaveDate, 0, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "LuggageCount", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CustomsImmigrationFieldIndex.LuggageCount, 0, 0, 10);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Nationality", typeof(System.String), false, false, false, true,  (int)CustomsImmigrationFieldIndex.Nationality, 100, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "PassportExpiredate", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CustomsImmigrationFieldIndex.PassportExpiredate, 0, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "PassportNo", typeof(System.String), false, false, false, true,  (int)CustomsImmigrationFieldIndex.PassportNo, 10485760, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Status", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CustomsImmigrationFieldIndex.Status, 0, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Transportation", typeof(System.String), false, false, false, true,  (int)CustomsImmigrationFieldIndex.Transportation, 200, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "TransportationNo", typeof(System.String), false, false, false, true,  (int)CustomsImmigrationFieldIndex.TransportationNo, 200, 0, 0);
			this.AddElementFieldInfo("CustomsImmigrationEntity", "Userid", typeof(System.String), false, false, false, false,  (int)CustomsImmigrationFieldIndex.Userid, 40, 0, 0);
		}

		/// <summary>Inits CustomsQuestionEntity's info objects</summary>
		private void InitCustomsQuestionEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CustomsQuestionFieldIndex), "CustomsQuestionEntity");
			this.AddElementFieldInfo("CustomsQuestionEntity", "Content", typeof(System.String), false, false, false, true,  (int)CustomsQuestionFieldIndex.Content, 4000, 0, 0);
			this.AddElementFieldInfo("CustomsQuestionEntity", "Id", typeof(System.String), true, false, false, false,  (int)CustomsQuestionFieldIndex.Id, 40, 0, 0);
			this.AddElementFieldInfo("CustomsQuestionEntity", "IsActive", typeof(Nullable<System.Boolean>), false, false, false, true,  (int)CustomsQuestionFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("CustomsQuestionEntity", "QuestionType", typeof(System.String), false, false, false, true,  (int)CustomsQuestionFieldIndex.QuestionType, 100, 0, 0);
		}

		/// <summary>Inits CustomsTaxisEntity's info objects</summary>
		private void InitCustomsTaxisEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CustomsTaxisFieldIndex), "CustomsTaxisEntity");
			this.AddElementFieldInfo("CustomsTaxisEntity", "HsCode", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CustomsTaxisFieldIndex.HsCode, 0, 0, 10);
			this.AddElementFieldInfo("CustomsTaxisEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)CustomsTaxisFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("CustomsTaxisEntity", "Name", typeof(System.String), false, false, false, true,  (int)CustomsTaxisFieldIndex.Name, 100, 0, 0);
			this.AddElementFieldInfo("CustomsTaxisEntity", "Origins", typeof(System.String), false, false, false, true,  (int)CustomsTaxisFieldIndex.Origins, 100, 0, 0);
			this.AddElementFieldInfo("CustomsTaxisEntity", "Quantity", typeof(Nullable<System.Int32>), false, false, false, true,  (int)CustomsTaxisFieldIndex.Quantity, 0, 0, 10);
			this.AddElementFieldInfo("CustomsTaxisEntity", "Type", typeof(System.String), false, false, false, true,  (int)CustomsTaxisFieldIndex.Type, 100, 0, 0);
			this.AddElementFieldInfo("CustomsTaxisEntity", "UsePurposes", typeof(System.String), false, false, false, true,  (int)CustomsTaxisFieldIndex.UsePurposes, 500, 0, 0);
			this.AddElementFieldInfo("CustomsTaxisEntity", "Value", typeof(Nullable<System.Decimal>), false, false, false, true,  (int)CustomsTaxisFieldIndex.Value, 0, 0, 0);
		}

		/// <summary>Inits CustomsUserAnswerEntity's info objects</summary>
		private void InitCustomsUserAnswerEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(CustomsUserAnswerFieldIndex), "CustomsUserAnswerEntity");
			this.AddElementFieldInfo("CustomsUserAnswerEntity", "AnswerId", typeof(System.String), true, false, false, false,  (int)CustomsUserAnswerFieldIndex.AnswerId, 40, 0, 0);
			this.AddElementFieldInfo("CustomsUserAnswerEntity", "AnswerText", typeof(System.String), false, false, false, true,  (int)CustomsUserAnswerFieldIndex.AnswerText, 1000, 0, 0);
			this.AddElementFieldInfo("CustomsUserAnswerEntity", "ChoiceId", typeof(System.String), false, true, false, true,  (int)CustomsUserAnswerFieldIndex.ChoiceId, 40, 0, 0);
			this.AddElementFieldInfo("CustomsUserAnswerEntity", "CreatedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)CustomsUserAnswerFieldIndex.CreatedAt, 0, 0, 0);
			this.AddElementFieldInfo("CustomsUserAnswerEntity", "ImmigrationFormId", typeof(System.String), false, true, false, false,  (int)CustomsUserAnswerFieldIndex.ImmigrationFormId, 40, 0, 0);
			this.AddElementFieldInfo("CustomsUserAnswerEntity", "QuestionId", typeof(System.String), false, true, false, true,  (int)CustomsUserAnswerFieldIndex.QuestionId, 40, 0, 0);
			this.AddElementFieldInfo("CustomsUserAnswerEntity", "UserId", typeof(System.String), false, false, false, false,  (int)CustomsUserAnswerFieldIndex.UserId, 40, 0, 0);
		}

		/// <summary>Inits NewsEntity's info objects</summary>
		private void InitNewsEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(NewsFieldIndex), "NewsEntity");
			this.AddElementFieldInfo("NewsEntity", "Content", typeof(System.String), false, false, false, true,  (int)NewsFieldIndex.Content, 1073741824, 0, 0);
			this.AddElementFieldInfo("NewsEntity", "Headline", typeof(System.String), false, false, false, true,  (int)NewsFieldIndex.Headline, 200, 0, 0);
			this.AddElementFieldInfo("NewsEntity", "Id", typeof(System.String), true, false, false, false,  (int)NewsFieldIndex.Id, 40, 0, 0);
			this.AddElementFieldInfo("NewsEntity", "NewsType", typeof(System.String), false, false, false, true,  (int)NewsFieldIndex.NewsType, 50, 0, 0);
		}
	}
}