//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using App.Xuatnhapcanh.Dal.EntityClasses;
using App.Xuatnhapcanh.Dal.HelperClasses;
using App.Xuatnhapcanh.Dal.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.Xuatnhapcanh.Dal.FactoryClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END


	/// <summary>general base class for the generated factories</summary>
	[Serializable]
	public partial class EntityFactoryBase2<TEntity> : EntityFactoryCore2
		where TEntity : EntityBase2, IEntity2
	{
		private readonly bool _isInHierarchy;

		/// <summary>CTor</summary>
		/// <param name="entityName">Name of the entity.</param>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <param name="isInHierarchy">If true, the entity of this factory is in an inheritance hierarchy, false otherwise</param>
		public EntityFactoryBase2(string entityName, App.Xuatnhapcanh.Dal.EntityType typeOfEntity, bool isInHierarchy) : base(entityName, (int)typeOfEntity)
		{
			_isInHierarchy = isInHierarchy;
		}
		
		/// <inheritdoc/>
		public override IEntityFields2 CreateFields() { return ModelInfoProviderSingleton.GetInstance().GetEntityFields(this.ForEntityName); }
		
		/// <inheritdoc/>
		public override IEntity2 CreateEntityFromEntityTypeValue(int entityTypeValue) {	return GeneralEntityFactory.Create((App.Xuatnhapcanh.Dal.EntityType)entityTypeValue); }

		/// <inheritdoc/>
		public override IRelationCollection CreateHierarchyRelations(string objectAlias) { return ModelInfoProviderSingleton.GetInstance().GetHierarchyRelations(this.ForEntityName, objectAlias); }

		/// <inheritdoc/>
		public override IEntityFactory2 GetEntityFactory(object[] fieldValues, Dictionary<string, int> entityFieldStartIndexesPerEntity) 
		{
			return (IEntityFactory2)ModelInfoProviderSingleton.GetInstance().GetEntityFactory(this.ForEntityName, fieldValues, entityFieldStartIndexesPerEntity) ?? this;
		}
		
		/// <inheritdoc/>
		public override IPredicateExpression GetEntityTypeFilter(bool negate, string objectAlias) {	return ModelInfoProviderSingleton.GetInstance().GetEntityTypeFilter(this.ForEntityName, objectAlias, negate);	}
						
		/// <inheritdoc/>
		public override IEntityCollection2 CreateEntityCollection()	{ return new EntityCollection<TEntity>(this); }
		
		/// <inheritdoc/>
		public override IEntityFields2 CreateHierarchyFields() 
		{
			return _isInHierarchy ? new EntityFields2(ModelInfoProviderSingleton.GetInstance().GetHierarchyFields(this.ForEntityName), ModelInfoProviderSingleton.GetInstance(), null) : base.CreateHierarchyFields();
		}
		
		/// <inheritdoc/>
		protected override Type ForEntityType { get { return typeof(TEntity); } }
	}

	/// <summary>Factory to create new, empty CustomsAnswerOptionEntity objects.</summary>
	[Serializable]
	public partial class CustomsAnswerOptionEntityFactory : EntityFactoryBase2<CustomsAnswerOptionEntity> 
	{
		/// <summary>CTor</summary>
		public CustomsAnswerOptionEntityFactory() : base("CustomsAnswerOptionEntity", App.Xuatnhapcanh.Dal.EntityType.CustomsAnswerOptionEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new CustomsAnswerOptionEntity(fields); }
	}

	/// <summary>Factory to create new, empty CustomsImmigrationEntity objects.</summary>
	[Serializable]
	public partial class CustomsImmigrationEntityFactory : EntityFactoryBase2<CustomsImmigrationEntity> 
	{
		/// <summary>CTor</summary>
		public CustomsImmigrationEntityFactory() : base("CustomsImmigrationEntity", App.Xuatnhapcanh.Dal.EntityType.CustomsImmigrationEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new CustomsImmigrationEntity(fields); }
	}

	/// <summary>Factory to create new, empty CustomsQuestionEntity objects.</summary>
	[Serializable]
	public partial class CustomsQuestionEntityFactory : EntityFactoryBase2<CustomsQuestionEntity> 
	{
		/// <summary>CTor</summary>
		public CustomsQuestionEntityFactory() : base("CustomsQuestionEntity", App.Xuatnhapcanh.Dal.EntityType.CustomsQuestionEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new CustomsQuestionEntity(fields); }
	}

	/// <summary>Factory to create new, empty CustomsTaxisEntity objects.</summary>
	[Serializable]
	public partial class CustomsTaxisEntityFactory : EntityFactoryBase2<CustomsTaxisEntity> 
	{
		/// <summary>CTor</summary>
		public CustomsTaxisEntityFactory() : base("CustomsTaxisEntity", App.Xuatnhapcanh.Dal.EntityType.CustomsTaxisEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new CustomsTaxisEntity(fields); }
	}

	/// <summary>Factory to create new, empty CustomsUserAnswerEntity objects.</summary>
	[Serializable]
	public partial class CustomsUserAnswerEntityFactory : EntityFactoryBase2<CustomsUserAnswerEntity> 
	{
		/// <summary>CTor</summary>
		public CustomsUserAnswerEntityFactory() : base("CustomsUserAnswerEntity", App.Xuatnhapcanh.Dal.EntityType.CustomsUserAnswerEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new CustomsUserAnswerEntity(fields); }
	}

	/// <summary>Factory to create new, empty NewsEntity objects.</summary>
	[Serializable]
	public partial class NewsEntityFactory : EntityFactoryBase2<NewsEntity> 
	{
		/// <summary>CTor</summary>
		public NewsEntityFactory() : base("NewsEntity", App.Xuatnhapcanh.Dal.EntityType.NewsEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new NewsEntity(fields); }
	}

	/// <summary>Factory to create new, empty Entity objects based on the entity type specified. Uses  entity specific factory objects</summary>
	[Serializable]
	public partial class GeneralEntityFactory
	{
		/// <summary>Creates a new, empty Entity object of the type specified</summary>
		/// <param name="entityTypeToCreate">The entity type to create.</param>
		/// <returns>A new, empty Entity object.</returns>
		public static IEntity2 Create(App.Xuatnhapcanh.Dal.EntityType entityTypeToCreate)
		{
			var factoryToUse = EntityFactoryFactory.GetFactory(entityTypeToCreate);
			IEntity2 toReturn = null;
			if(factoryToUse != null)
			{
				toReturn = factoryToUse.Create();
			}
			return toReturn;
		}		
	}
		
	/// <summary>Class which is used to obtain the entity factory based on the .NET type of the entity. </summary>
	[Serializable]
	public static class EntityFactoryFactory
	{
		private static Dictionary<Type, IEntityFactory2> _factoryPerType = new Dictionary<Type, IEntityFactory2>();

		/// <summary>Initializes the <see cref="EntityFactoryFactory"/> class.</summary>
		static EntityFactoryFactory()
		{
			foreach(int entityTypeValue in Enum.GetValues(typeof(App.Xuatnhapcanh.Dal.EntityType)))
			{
				var factory = GetFactory((App.Xuatnhapcanh.Dal.EntityType)entityTypeValue);
				_factoryPerType.Add(factory.ForEntityType ?? factory.Create().GetType(), factory);
			}
		}

		/// <summary>Gets the factory of the entity with the .NET type specified</summary>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <returns>factory to use or null if not found</returns>
		public static IEntityFactory2 GetFactory(Type typeOfEntity) { return _factoryPerType.GetValue(typeOfEntity); }

		/// <summary>Gets the factory of the entity with the App.Xuatnhapcanh.Dal.EntityType specified</summary>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <returns>factory to use or null if not found</returns>
		public static IEntityFactory2 GetFactory(App.Xuatnhapcanh.Dal.EntityType typeOfEntity)
		{
			switch(typeOfEntity)
			{
				case App.Xuatnhapcanh.Dal.EntityType.CustomsAnswerOptionEntity:
					return new CustomsAnswerOptionEntityFactory();
				case App.Xuatnhapcanh.Dal.EntityType.CustomsImmigrationEntity:
					return new CustomsImmigrationEntityFactory();
				case App.Xuatnhapcanh.Dal.EntityType.CustomsQuestionEntity:
					return new CustomsQuestionEntityFactory();
				case App.Xuatnhapcanh.Dal.EntityType.CustomsTaxisEntity:
					return new CustomsTaxisEntityFactory();
				case App.Xuatnhapcanh.Dal.EntityType.CustomsUserAnswerEntity:
					return new CustomsUserAnswerEntityFactory();
				case App.Xuatnhapcanh.Dal.EntityType.NewsEntity:
					return new NewsEntityFactory();
				default:
					return null;
			}
		}
	}
		
	/// <summary>Element creator for creating project elements from somewhere else, like inside Linq providers.</summary>
	public class ElementCreator : ElementCreatorBase, IElementCreator2
	{
		/// <summary>Gets the factory of the Entity type with the App.Xuatnhapcanh.Dal.EntityType value passed in</summary>
		/// <param name="entityTypeValue">The entity type value.</param>
		/// <returns>the entity factory of the entity type or null if not found</returns>
		public IEntityFactory2 GetFactory(int entityTypeValue) { return (IEntityFactory2)this.GetFactoryImpl(entityTypeValue); }
		
		/// <summary>Gets the factory of the Entity type with the .NET type passed in</summary>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <returns>the entity factory of the entity type or null if not found</returns>
		public IEntityFactory2 GetFactory(Type typeOfEntity) { return (IEntityFactory2)this.GetFactoryImpl(typeOfEntity); }

		/// <summary>Creates a new resultset fields object with the number of field slots reserved as specified</summary>
		/// <param name="numberOfFields">The number of fields.</param>
		/// <returns>ready to use resultsetfields object</returns>
		public IEntityFields2 CreateResultsetFields(int numberOfFields) { return new ResultsetFields(numberOfFields); }
		
		/// <inheritdoc/>
		public override IInheritanceInfoProvider ObtainInheritanceInfoProviderInstance() { return ModelInfoProviderSingleton.GetInstance(); }

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(DerivedTableDefinition leftOperand) { return new DynamicRelation(leftOperand); }

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(DerivedTableDefinition leftOperand, JoinHint joinType, DerivedTableDefinition rightOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, rightOperand, onClause);
		}

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(IEntityFieldCore leftOperand, JoinHint joinType, DerivedTableDefinition rightOperand, string aliasLeftOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, rightOperand, aliasLeftOperand, onClause);
		}

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(DerivedTableDefinition leftOperand, JoinHint joinType, string rightOperandEntityName, string aliasRightOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, (App.Xuatnhapcanh.Dal.EntityType)Enum.Parse(typeof(App.Xuatnhapcanh.Dal.EntityType), rightOperandEntityName, false), aliasRightOperand, onClause);
		}

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(string leftOperandEntityName, JoinHint joinType, string rightOperandEntityName, string aliasLeftOperand, string aliasRightOperand, IPredicate onClause)
		{
			return new DynamicRelation((App.Xuatnhapcanh.Dal.EntityType)Enum.Parse(typeof(App.Xuatnhapcanh.Dal.EntityType), leftOperandEntityName, false), joinType, (App.Xuatnhapcanh.Dal.EntityType)Enum.Parse(typeof(App.Xuatnhapcanh.Dal.EntityType), rightOperandEntityName, false), aliasLeftOperand, aliasRightOperand, onClause);
		}
		
		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(IEntityFieldCore leftOperand, JoinHint joinType, string rightOperandEntityName, string aliasLeftOperand, string aliasRightOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, (App.Xuatnhapcanh.Dal.EntityType)Enum.Parse(typeof(App.Xuatnhapcanh.Dal.EntityType), rightOperandEntityName, false), aliasLeftOperand, aliasRightOperand, onClause);
		}
		
		/// <inheritdoc/>
		protected override IEntityFactoryCore GetFactoryImpl(int entityTypeValue) { return EntityFactoryFactory.GetFactory((App.Xuatnhapcanh.Dal.EntityType)entityTypeValue); }

		/// <inheritdoc/>
		protected override IEntityFactoryCore GetFactoryImpl(Type typeOfEntity) { return EntityFactoryFactory.GetFactory(typeOfEntity);	}

	}
}
