//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using App.Xuatnhapcanh.Dal.EntityClasses;
using App.Xuatnhapcanh.Dal.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace App.Xuatnhapcanh.Dal.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the CustomsAnswerOption entity</summary>
		public EntityQuery<CustomsAnswerOptionEntity> CustomsAnswerOption { get { return Create<CustomsAnswerOptionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CustomsImmigration entity</summary>
		public EntityQuery<CustomsImmigrationEntity> CustomsImmigration { get { return Create<CustomsImmigrationEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CustomsQuestion entity</summary>
		public EntityQuery<CustomsQuestionEntity> CustomsQuestion { get { return Create<CustomsQuestionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CustomsTaxis entity</summary>
		public EntityQuery<CustomsTaxisEntity> CustomsTaxis { get { return Create<CustomsTaxisEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CustomsUserAnswer entity</summary>
		public EntityQuery<CustomsUserAnswerEntity> CustomsUserAnswer { get { return Create<CustomsUserAnswerEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the News entity</summary>
		public EntityQuery<NewsEntity> News { get { return Create<NewsEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}