//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.Xuatnhapcanh.Dal.HelperClasses;
using App.Xuatnhapcanh.Dal.FactoryClasses;
using App.Xuatnhapcanh.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.Xuatnhapcanh.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'CustomsTaxis'.<br/><br/></summary>
	[Serializable]
	public partial class CustomsTaxisEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static CustomsTaxisEntityStaticMetaData _staticMetaData = new CustomsTaxisEntityStaticMetaData();
		private static CustomsTaxisRelations _relationsFactory = new CustomsTaxisRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CustomsTaxisEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CustomsTaxisEntityStaticMetaData()
			{
				SetEntityCoreInfo("CustomsTaxisEntity", InheritanceHierarchyType.None, false, (int)App.Xuatnhapcanh.Dal.EntityType.CustomsTaxisEntity, typeof(CustomsTaxisEntity), typeof(CustomsTaxisEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static CustomsTaxisEntity()
		{
		}

		/// <summary> CTor</summary>
		public CustomsTaxisEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CustomsTaxisEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CustomsTaxisEntity</param>
		public CustomsTaxisEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CustomsTaxis which data should be fetched into this CustomsTaxis object</param>
		public CustomsTaxisEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CustomsTaxis which data should be fetched into this CustomsTaxis object</param>
		/// <param name="validator">The custom validator object for this CustomsTaxisEntity</param>
		public CustomsTaxisEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CustomsTaxisEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CustomsTaxisEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CustomsTaxisRelations Relations { get { return _relationsFactory; } }

		/// <summary>The HsCode property of the Entity CustomsTaxis<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_taxes"."hs_code".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> HsCode
		{
			get { return (Nullable<System.Int32>)GetValue((int)CustomsTaxisFieldIndex.HsCode, false); }
			set { SetValue((int)CustomsTaxisFieldIndex.HsCode, value); }
		}

		/// <summary>The Id property of the Entity CustomsTaxis<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_taxes"."id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)CustomsTaxisFieldIndex.Id, true); }
			set { SetValue((int)CustomsTaxisFieldIndex.Id, value); }
		}

		/// <summary>The Name property of the Entity CustomsTaxis<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_taxes"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)CustomsTaxisFieldIndex.Name, true); }
			set { SetValue((int)CustomsTaxisFieldIndex.Name, value); }
		}

		/// <summary>The Origins property of the Entity CustomsTaxis<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_taxes"."origins".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Origins
		{
			get { return (System.String)GetValue((int)CustomsTaxisFieldIndex.Origins, true); }
			set { SetValue((int)CustomsTaxisFieldIndex.Origins, value); }
		}

		/// <summary>The Quantity property of the Entity CustomsTaxis<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_taxes"."quantity".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Quantity
		{
			get { return (Nullable<System.Int32>)GetValue((int)CustomsTaxisFieldIndex.Quantity, false); }
			set { SetValue((int)CustomsTaxisFieldIndex.Quantity, value); }
		}

		/// <summary>The Type property of the Entity CustomsTaxis<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_taxes"."type".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Type
		{
			get { return (System.String)GetValue((int)CustomsTaxisFieldIndex.Type, true); }
			set { SetValue((int)CustomsTaxisFieldIndex.Type, value); }
		}

		/// <summary>The UsePurposes property of the Entity CustomsTaxis<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_taxes"."use_purposes".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String UsePurposes
		{
			get { return (System.String)GetValue((int)CustomsTaxisFieldIndex.UsePurposes, true); }
			set { SetValue((int)CustomsTaxisFieldIndex.UsePurposes, value); }
		}

		/// <summary>The Value property of the Entity CustomsTaxis<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_taxes"."value".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> Value
		{
			get { return (Nullable<System.Decimal>)GetValue((int)CustomsTaxisFieldIndex.Value, false); }
			set { SetValue((int)CustomsTaxisFieldIndex.Value, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace App.Xuatnhapcanh.Dal
{
	public enum CustomsTaxisFieldIndex
	{
		///<summary>HsCode. </summary>
		HsCode,
		///<summary>Id. </summary>
		Id,
		///<summary>Name. </summary>
		Name,
		///<summary>Origins. </summary>
		Origins,
		///<summary>Quantity. </summary>
		Quantity,
		///<summary>Type. </summary>
		Type,
		///<summary>UsePurposes. </summary>
		UsePurposes,
		///<summary>Value. </summary>
		Value,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.Xuatnhapcanh.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: CustomsTaxis. </summary>
	public partial class CustomsTaxisRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCustomsTaxisRelations
	{

		/// <summary>CTor</summary>
		static StaticCustomsTaxisRelations() { }
	}
}
