//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.Xuatnhapcanh.Dal.HelperClasses;
using App.Xuatnhapcanh.Dal.FactoryClasses;
using App.Xuatnhapcanh.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.Xuatnhapcanh.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'CustomsImmigration'.<br/><br/></summary>
	[Serializable]
	public partial class CustomsImmigrationEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<CustomsUserAnswerEntity> _customsUserAnswers;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static CustomsImmigrationEntityStaticMetaData _staticMetaData = new CustomsImmigrationEntityStaticMetaData();
		private static CustomsImmigrationRelations _relationsFactory = new CustomsImmigrationRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name CustomsUserAnswers</summary>
			public static readonly string CustomsUserAnswers = "CustomsUserAnswers";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CustomsImmigrationEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CustomsImmigrationEntityStaticMetaData()
			{
				SetEntityCoreInfo("CustomsImmigrationEntity", InheritanceHierarchyType.None, false, (int)App.Xuatnhapcanh.Dal.EntityType.CustomsImmigrationEntity, typeof(CustomsImmigrationEntity), typeof(CustomsImmigrationEntityFactory), false);
				AddNavigatorMetaData<CustomsImmigrationEntity, EntityCollection<CustomsUserAnswerEntity>>("CustomsUserAnswers", a => a._customsUserAnswers, (a, b) => a._customsUserAnswers = b, a => a.CustomsUserAnswers, () => new CustomsImmigrationRelations().CustomsUserAnswerEntityUsingImmigrationFormId, typeof(CustomsUserAnswerEntity), (int)App.Xuatnhapcanh.Dal.EntityType.CustomsUserAnswerEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CustomsImmigrationEntity()
		{
		}

		/// <summary> CTor</summary>
		public CustomsImmigrationEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CustomsImmigrationEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CustomsImmigrationEntity</param>
		public CustomsImmigrationEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CustomsImmigration which data should be fetched into this CustomsImmigration object</param>
		public CustomsImmigrationEntity(System.String id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CustomsImmigration which data should be fetched into this CustomsImmigration object</param>
		/// <param name="validator">The custom validator object for this CustomsImmigrationEntity</param>
		public CustomsImmigrationEntity(System.String id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CustomsImmigrationEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'CustomsUserAnswer' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCustomsUserAnswers() { return CreateRelationInfoForNavigator("CustomsUserAnswers"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CustomsImmigrationEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CustomsImmigrationRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CustomsUserAnswer' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCustomsUserAnswers { get { return _staticMetaData.GetPrefetchPathElement("CustomsUserAnswers", CommonEntityBase.CreateEntityCollection<CustomsUserAnswerEntity>()); } }

		/// <summary>The Address property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."address".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Address
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.Address, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Address, value); }
		}

		/// <summary>The Cash property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."cash".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> Cash
		{
			get { return (Nullable<System.Boolean>)GetValue((int)CustomsImmigrationFieldIndex.Cash, false); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Cash, value); }
		}

		/// <summary>The CityFrom property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."city_from".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 300.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CityFrom
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.CityFrom, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.CityFrom, value); }
		}

		/// <summary>The CityTo property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."city_to".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 300.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CityTo
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.CityTo, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.CityTo, value); }
		}

		/// <summary>The Dob property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."dob".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> Dob
		{
			get { return (Nullable<System.DateTime>)GetValue((int)CustomsImmigrationFieldIndex.Dob, false); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Dob, value); }
		}

		/// <summary>The Email property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."email".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Email
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.Email, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Email, value); }
		}

		/// <summary>The EntryDate property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."entry_date".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> EntryDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)CustomsImmigrationFieldIndex.EntryDate, false); }
			set { SetValue((int)CustomsImmigrationFieldIndex.EntryDate, value); }
		}

		/// <summary>The FirstName property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."first_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 40.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String FirstName
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.FirstName, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.FirstName, value); }
		}

		/// <summary>The Gender property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."gender".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> Gender
		{
			get { return (Nullable<System.Boolean>)GetValue((int)CustomsImmigrationFieldIndex.Gender, false); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Gender, value); }
		}

		/// <summary>The Goods property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."goods".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> Goods
		{
			get { return (Nullable<System.Boolean>)GetValue((int)CustomsImmigrationFieldIndex.Goods, false); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Goods, value); }
		}

		/// <summary>The HotelName property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."hotel_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String HotelName
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.HotelName, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.HotelName, value); }
		}

		/// <summary>The Id property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."id".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 40.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Id
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.Id, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Id, value); }
		}

		/// <summary>The Jewellery property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."jewellery".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> Jewellery
		{
			get { return (Nullable<System.Boolean>)GetValue((int)CustomsImmigrationFieldIndex.Jewellery, false); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Jewellery, value); }
		}

		/// <summary>The LaneAssignment property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."lane_assignment".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> LaneAssignment
		{
			get { return (Nullable<System.Boolean>)GetValue((int)CustomsImmigrationFieldIndex.LaneAssignment, false); }
			set { SetValue((int)CustomsImmigrationFieldIndex.LaneAssignment, value); }
		}

		/// <summary>The LastName property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."last_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 40.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String LastName
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.LastName, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.LastName, value); }
		}

		/// <summary>The LeaveDate property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."leave_date".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> LeaveDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)CustomsImmigrationFieldIndex.LeaveDate, false); }
			set { SetValue((int)CustomsImmigrationFieldIndex.LeaveDate, value); }
		}

		/// <summary>The LuggageCount property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."luggage_count".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> LuggageCount
		{
			get { return (Nullable<System.Int32>)GetValue((int)CustomsImmigrationFieldIndex.LuggageCount, false); }
			set { SetValue((int)CustomsImmigrationFieldIndex.LuggageCount, value); }
		}

		/// <summary>The Nationality property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."nationality".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Nationality
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.Nationality, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Nationality, value); }
		}

		/// <summary>The PassportExpiredate property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."passport_expiredate".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> PassportExpiredate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)CustomsImmigrationFieldIndex.PassportExpiredate, false); }
			set { SetValue((int)CustomsImmigrationFieldIndex.PassportExpiredate, value); }
		}

		/// <summary>The PassportNo property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."passport_no".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String PassportNo
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.PassportNo, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.PassportNo, value); }
		}

		/// <summary>The Status property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."status".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Boolean> Status
		{
			get { return (Nullable<System.Boolean>)GetValue((int)CustomsImmigrationFieldIndex.Status, false); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Status, value); }
		}

		/// <summary>The Transportation property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."transportation".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Transportation
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.Transportation, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Transportation, value); }
		}

		/// <summary>The TransportationNo property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."transportation_No".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String TransportationNo
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.TransportationNo, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.TransportationNo, value); }
		}

		/// <summary>The Userid property of the Entity CustomsImmigration<br/><br/></summary>
		/// <remarks>Mapped on  table field: "customs_immigration"."userid".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 40.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Userid
		{
			get { return (System.String)GetValue((int)CustomsImmigrationFieldIndex.Userid, true); }
			set { SetValue((int)CustomsImmigrationFieldIndex.Userid, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'CustomsUserAnswerEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CustomsUserAnswerEntity))]
		public virtual EntityCollection<CustomsUserAnswerEntity> CustomsUserAnswers { get { return GetOrCreateEntityCollection<CustomsUserAnswerEntity, CustomsUserAnswerEntityFactory>("CustomsImmigration", true, false, ref _customsUserAnswers); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace App.Xuatnhapcanh.Dal
{
	public enum CustomsImmigrationFieldIndex
	{
		///<summary>Address. </summary>
		Address,
		///<summary>Cash. </summary>
		Cash,
		///<summary>CityFrom. </summary>
		CityFrom,
		///<summary>CityTo. </summary>
		CityTo,
		///<summary>Dob. </summary>
		Dob,
		///<summary>Email. </summary>
		Email,
		///<summary>EntryDate. </summary>
		EntryDate,
		///<summary>FirstName. </summary>
		FirstName,
		///<summary>Gender. </summary>
		Gender,
		///<summary>Goods. </summary>
		Goods,
		///<summary>HotelName. </summary>
		HotelName,
		///<summary>Id. </summary>
		Id,
		///<summary>Jewellery. </summary>
		Jewellery,
		///<summary>LaneAssignment. </summary>
		LaneAssignment,
		///<summary>LastName. </summary>
		LastName,
		///<summary>LeaveDate. </summary>
		LeaveDate,
		///<summary>LuggageCount. </summary>
		LuggageCount,
		///<summary>Nationality. </summary>
		Nationality,
		///<summary>PassportExpiredate. </summary>
		PassportExpiredate,
		///<summary>PassportNo. </summary>
		PassportNo,
		///<summary>Status. </summary>
		Status,
		///<summary>Transportation. </summary>
		Transportation,
		///<summary>TransportationNo. </summary>
		TransportationNo,
		///<summary>Userid. </summary>
		Userid,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.Xuatnhapcanh.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: CustomsImmigration. </summary>
	public partial class CustomsImmigrationRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between CustomsImmigrationEntity and CustomsUserAnswerEntity over the 1:n relation they have, using the relation between the fields: CustomsImmigration.Id - CustomsUserAnswer.ImmigrationFormId</summary>
		public virtual IEntityRelation CustomsUserAnswerEntityUsingImmigrationFormId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "CustomsUserAnswers", true, new[] { CustomsImmigrationFields.Id, CustomsUserAnswerFields.ImmigrationFormId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCustomsImmigrationRelations
	{
		internal static readonly IEntityRelation CustomsUserAnswerEntityUsingImmigrationFormIdStatic = new CustomsImmigrationRelations().CustomsUserAnswerEntityUsingImmigrationFormId;

		/// <summary>CTor</summary>
		static StaticCustomsImmigrationRelations() { }
	}
}
