//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.Xuatnhapcanh.Dal.HelperClasses;
using App.Xuatnhapcanh.Dal.FactoryClasses;
using App.Xuatnhapcanh.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.Xuatnhapcanh.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'News'.<br/><br/></summary>
	[Serializable]
	public partial class NewsEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static NewsEntityStaticMetaData _staticMetaData = new NewsEntityStaticMetaData();
		private static NewsRelations _relationsFactory = new NewsRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class NewsEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public NewsEntityStaticMetaData()
			{
				SetEntityCoreInfo("NewsEntity", InheritanceHierarchyType.None, false, (int)App.Xuatnhapcanh.Dal.EntityType.NewsEntity, typeof(NewsEntity), typeof(NewsEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static NewsEntity()
		{
		}

		/// <summary> CTor</summary>
		public NewsEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public NewsEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this NewsEntity</param>
		public NewsEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for News which data should be fetched into this News object</param>
		public NewsEntity(System.String id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for News which data should be fetched into this News object</param>
		/// <param name="validator">The custom validator object for this NewsEntity</param>
		public NewsEntity(System.String id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected NewsEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this NewsEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static NewsRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Content property of the Entity News<br/><br/></summary>
		/// <remarks>Mapped on  table field: "news"."content".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Content
		{
			get { return (System.String)GetValue((int)NewsFieldIndex.Content, true); }
			set { SetValue((int)NewsFieldIndex.Content, value); }
		}

		/// <summary>The Headline property of the Entity News<br/><br/></summary>
		/// <remarks>Mapped on  table field: "news"."headline".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Headline
		{
			get { return (System.String)GetValue((int)NewsFieldIndex.Headline, true); }
			set { SetValue((int)NewsFieldIndex.Headline, value); }
		}

		/// <summary>The Id property of the Entity News<br/><br/></summary>
		/// <remarks>Mapped on  table field: "news"."id".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 40.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Id
		{
			get { return (System.String)GetValue((int)NewsFieldIndex.Id, true); }
			set { SetValue((int)NewsFieldIndex.Id, value); }
		}

		/// <summary>The NewsType property of the Entity News<br/><br/></summary>
		/// <remarks>Mapped on  table field: "news"."news_type".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String NewsType
		{
			get { return (System.String)GetValue((int)NewsFieldIndex.NewsType, true); }
			set { SetValue((int)NewsFieldIndex.NewsType, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace App.Xuatnhapcanh.Dal
{
	public enum NewsFieldIndex
	{
		///<summary>Content. </summary>
		Content,
		///<summary>Headline. </summary>
		Headline,
		///<summary>Id. </summary>
		Id,
		///<summary>NewsType. </summary>
		NewsType,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.Xuatnhapcanh.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: News. </summary>
	public partial class NewsRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticNewsRelations
	{

		/// <summary>CTor</summary>
		static StaticNewsRelations() { }
	}
}
