//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.11.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.Xuatnhapcanh.Dal.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal partial class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitCustomsAnswerOptionEntityMappings();
			InitCustomsImmigrationEntityMappings();
			InitCustomsQuestionEntityMappings();
			InitCustomsTaxisEntityMappings();
			InitCustomsUserAnswerEntityMappings();
			InitNewsEntityMappings();
		}

		/// <summary>Inits CustomsAnswerOptionEntity's mappings</summary>
		private void InitCustomsAnswerOptionEntityMappings()
		{
			this.AddElementMapping("CustomsAnswerOptionEntity", @"XUATNHAPCANH", @"appxnc", "customs_answer_option", 4, 0);
			this.AddElementFieldMapping("CustomsAnswerOptionEntity", "Content", "content", false, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("CustomsAnswerOptionEntity", "DetailRequired", "detail_required", true, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
			this.AddElementFieldMapping("CustomsAnswerOptionEntity", "Id", "id", false, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("CustomsAnswerOptionEntity", "QuestionId", "question_id", true, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits CustomsImmigrationEntity's mappings</summary>
		private void InitCustomsImmigrationEntityMappings()
		{
			this.AddElementMapping("CustomsImmigrationEntity", @"XUATNHAPCANH", @"appxnc", "customs_immigration", 24, 0);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Address", "address", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Cash", "cash", true, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 1);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "CityFrom", "city_from", true, "Varchar", 300, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "CityTo", "city_to", true, "Varchar", 300, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Dob", "dob", true, "Date", 0, 0, 0, false, "", null, typeof(System.DateTime), 4);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Email", "email", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "EntryDate", "entry_date", true, "Date", 0, 0, 0, false, "", null, typeof(System.DateTime), 6);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "FirstName", "first_name", true, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Gender", "gender", true, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 8);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Goods", "goods", true, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 9);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "HotelName", "hotel_name", true, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Id", "id", false, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Jewellery", "jewellery", true, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 12);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "LaneAssignment", "lane_assignment", true, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 13);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "LastName", "last_name", true, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "LeaveDate", "leave_date", true, "Date", 0, 0, 0, false, "", null, typeof(System.DateTime), 15);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "LuggageCount", "luggage_count", true, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 16);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Nationality", "nationality", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 17);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "PassportExpiredate", "passport_expiredate", true, "Date", 0, 0, 0, false, "", null, typeof(System.DateTime), 18);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "PassportNo", "passport_no", true, "Varchar", 10485760, 0, 0, false, "", null, typeof(System.String), 19);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Status", "status", true, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 20);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Transportation", "transportation", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 21);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "TransportationNo", "transportation_No", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 22);
			this.AddElementFieldMapping("CustomsImmigrationEntity", "Userid", "userid", false, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 23);
		}

		/// <summary>Inits CustomsQuestionEntity's mappings</summary>
		private void InitCustomsQuestionEntityMappings()
		{
			this.AddElementMapping("CustomsQuestionEntity", @"XUATNHAPCANH", @"appxnc", "customs_question", 4, 0);
			this.AddElementFieldMapping("CustomsQuestionEntity", "Content", "content", true, "Varchar", 4000, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("CustomsQuestionEntity", "Id", "id", false, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("CustomsQuestionEntity", "IsActive", "is_active", true, "Boolean", 0, 0, 0, false, "", null, typeof(System.Boolean), 2);
			this.AddElementFieldMapping("CustomsQuestionEntity", "QuestionType", "question_type", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits CustomsTaxisEntity's mappings</summary>
		private void InitCustomsTaxisEntityMappings()
		{
			this.AddElementMapping("CustomsTaxisEntity", @"XUATNHAPCANH", @"appxnc", "customs_taxes", 8, 0);
			this.AddElementFieldMapping("CustomsTaxisEntity", "HsCode", "hs_code", true, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("CustomsTaxisEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "appxnc.customs_taxes_id_seq", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("CustomsTaxisEntity", "Name", "name", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("CustomsTaxisEntity", "Origins", "origins", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("CustomsTaxisEntity", "Quantity", "quantity", true, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 4);
			this.AddElementFieldMapping("CustomsTaxisEntity", "Type", "type", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("CustomsTaxisEntity", "UsePurposes", "use_purposes", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("CustomsTaxisEntity", "Value", "value", true, "Numeric", 0, 0, 0, false, "", null, typeof(System.Decimal), 7);
		}

		/// <summary>Inits CustomsUserAnswerEntity's mappings</summary>
		private void InitCustomsUserAnswerEntityMappings()
		{
			this.AddElementMapping("CustomsUserAnswerEntity", @"XUATNHAPCANH", @"appxnc", "customs_user_answer", 7, 0);
			this.AddElementFieldMapping("CustomsUserAnswerEntity", "AnswerId", "answer_id", false, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("CustomsUserAnswerEntity", "AnswerText", "answer_text", true, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("CustomsUserAnswerEntity", "ChoiceId", "choice_id", true, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("CustomsUserAnswerEntity", "CreatedAt", "created_at", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 3);
			this.AddElementFieldMapping("CustomsUserAnswerEntity", "ImmigrationFormId", "immigration_form_id", false, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("CustomsUserAnswerEntity", "QuestionId", "question_id", true, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("CustomsUserAnswerEntity", "UserId", "user_id", false, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 6);
		}

		/// <summary>Inits NewsEntity's mappings</summary>
		private void InitNewsEntityMappings()
		{
			this.AddElementMapping("NewsEntity", @"XUATNHAPCANH", @"appxnc", "news", 4, 0);
			this.AddElementFieldMapping("NewsEntity", "Content", "content", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("NewsEntity", "Headline", "headline", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("NewsEntity", "Id", "id", false, "Varchar", 40, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("NewsEntity", "NewsType", "news_type", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 3);
		}

	}
}
